name: entry_kit
description: A production-ready authentication UI package. Decouples UI from logic with interfaces for Google & Apple auth.
version: 0.0.9
homepage: https://github.com/jeffbezosriyal/entry_kit
repository: https://github.com/jeffbezosriyal/entry_kit
issue_tracker: https://github.com/jeffbezosriyal/entry_kit/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  # Core Logic
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7

  # UI Assets
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.7
  mocktail: ^1.0.4
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/google_logo.svg